//
// Created by galti on 15/11/2024.
//
int reprendre_une_partie(){
// APPEL PLATEAU
// APPEL PLACEMENT DU PION DANS LA BASE DE DONNEES
// APPEL PLACEMENTS DES BARRIERES DANS LA BASE DE DONNEES
// APPEL DE L'ORDRE DES JOUEURS + QUI DOIT JOUER
}
#include "reprendre une partie.h"
